config/routes.rb
Rails.application.routes.draw do
  resources :videos
  devise_for :users, :skip => [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  scope '/admin' do
    resources :users
    post '/users/:id/resetpassword', to: 'users#resetpassword', as: 'reset_user_password'
    post '/users/:id/toggleadmin', to: 'users#toggleadmin', as: 'toggle_user_admin'
  end

  get 'welcome/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'videos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :blob
  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def verify_admin
    if current_user.admin != 1
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin

  def index
    @users = User.order(email: :asc)
  end
  
  def new
    @user = User.new
  end

  def create
    @password = Devise.friendly_token.first(20)
    admin = 0 # Subscriber
    admin = 1 if params[:user][:role] == "admin"
    email = params[:user][:email]
    name = params[:user][:name]
    @user = User.create!( 
      email: email,
      name: name,
      admin: admin,
      password: @password,
    )
    @verb = "created"
    render :show
  end

  def resetpassword
    @password = Devise.friendly_token.first(20)
    @user = User.find(params[:id])
    @user.update_attributes(password: @password)
    @verb = "updated"
    render :show
  end

  def toggleadmin
    @user = User.find(params[:id])
    @user.admin = (@user.admin + 1) % 2 #toggle between 1 (Admin), and 0 (Normal)
    @user.save
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end


end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
## Comments for changes required to allow unauthenticted uploads from external script
#  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :verify_admin, except: [:index, :show]#, :create]
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    if params[:query]
      @videos = search_videos(params[:query]).order(date: :desc).page(params[:page])
    else
      @videos = Video.order(date: :desc).page(params[:page])
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.blob.attach(params[:video][:blob])
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :date)
    end

    def search_videos(query)
      videos = Video.where('title LIKE ?', "%#{query}%")
      videos
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Family Videos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav>
    <header>
      <%=link_to "Home", root_path, class: 'navigation-home' %>
        <% if user_signed_in? %>
          <% if current_user.admin == 1 %>
            <%= link_to "Users", users_path %>
          <% end %>
          <%= link_to "Account", edit_user_registration_path %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
        <% end %>
    </header>
    </nav>

    <div class="container">
      <% if notice and !notice.empty? %>
        <p class="notice"><%= notice %><span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span></p>
      <% end %>
      <% if alert and !alert.empty? %>
        <p class="alert"><%= alert %><span class="closebtn" onclick="this.parentElement.st
yl  e.display='none';">&times;</span></p>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/users/index.html.erb
<h2>Manage Users</h2>
<%= link_to "New User", new_user_path %>
<hr>
<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Role</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%=user.email%></td>
      <td><%=user.name%></td>
      <td><%= if user.admin == 1
                "Admin" 
              elsif user.admin == 2
                "Publisher"
              else
                "Subscriber"
              end %></td>
      <td>
        <% if user == current_user %>
          <%= link_to "Change Password",
            edit_user_registration_path,
            class: 'nowrap' %> 
        <% else %>
          <%= link_to "Change Role", 
            toggle_user_admin_path(user),
            method: :post,
            class: 'nowrap' %> |
          <%= link_to 'Reset Password', reset_user_password_path(user),
            method: :post, class: 'nowrap' %> |
          <%= link_to 'Delete', user_path(user),
            method: :delete, class: 'nowrap',
            data: { confirm: "Are you sure you want to delete #{user.name} with email: #{user.email}?" } %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :role %><br>
    <%= form.radio_button :role, 'subscriber', checked: true %>Subscriber<br />
    <%= form.radio_button :role, 'admin' %>Admin<br />
  </p>  
 
  <p>
    <%= form.submit value: "Create User" %>
  </p>
 
<% end %>
 
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>User successfully <%=@verb%></p>

<%= link_to "Back", users_path %>

<hr>

<strong>Name:</strong> <%= @user.name %><br>
<strong>Email:</strong> <%= @user.email %><br>
<strong>Password:</strong> <%= @password %><br>
<hr>
Please share this login information with <%= @user.name %>.

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.file_field :blob, :accept => ".mp4" %>
  </div>

  <div class="actions">
    <%= form.submit :value=> "Upload Video" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.admin? %>
  <%= link_to 'New Video', new_video_path %>
<% end %>

<h1>Videos</h1>

<%= form_tag(videos_path, method: :get) do %>
  Search for Video: <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search", query: nil %>
<% end %>

<% @videos.each do |video| %>
  <h2><%= link_to video.title, video %></h2>
  <% if video.blob.previewable? %>
    <%= link_to(image_tag(video.blob.preview(resize: 360)), video) %>
  <% end %>
<% end %>

<%= paginate @videos %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @video.title %></h2>
</p>

<p>
  <video controls>
  <source src="<%= url_for(@video.blob) %>" type="video/mp4">
  </video>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @video.date.strftime("%B %-d, %Y") %>
</p>

<%= link_to 'Back', videos_path %> 
<% if current_user.admin? %>
  | <%= link_to 'Edit', edit_video_path(@video) %>
  | <%= link_to 'Delete', video_path(@video),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>